### ISSUE TITLE
Po vyplnění API klíče dochází k "Allowed memory size exhausted"

### ISSUE THREAD

**Issue by 8915b** [oerdnj/woocommerce-zasilkovna#21]
Zdravím všechny. 
Prosím o pomoc s řešením problému, kdy plugin Zásilkovna vyžaduje velké množství paměti. **Dokud není do pluginu zadán klíč API** není s pluginem žádný problém. Jakmile je vyplněn API klíč objeví se problém s pamětí. Můžete mi poradit co s tím?

**hláška**
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 67670056 bytes) in /www/doc/www.adatto.cz/www/mttest/wp-includes/wp-db.php on line 3333

**Podmínky:**
Je to testovací web **_= není tam vůbec nic a jen jeden produkt_** nainstalován pouze wordpress 5.6, Woocommerce 4.8.0, Zásilkovna Verze 0.1.1., šablona Twenty Twenty-OneVerze: 1.0. nic víc.
testweb: http://adatto.cz/mttest/obchod/

Moc děkuji za jakoukoliv radu.
Marcel

**Comment by morvy** [comment]
No kym nedas kluc, tak ani nenatiahne pobocky zo Zasielkovne a teda to vlastne vobec nespusti a nefunguje.. a ked ten kluc das a vyzerie to RAM, tak tam zjavne nieco nefunguje dobre, ale 256MB by naozaj malo stacit, mozno by som skusil downgrade Woo na 4.7.1

**Comment by 8915b** [comment]
@morvy Jasný, já to uvádím proto, že jakožto lama se snažím dodat veškeré informace, co by vývojáři mohli potřebovat. Ikdyž tomu prd rozumím, přijde mi, že chyba je v načítání toho xml feedu. 
**Zkusil jsem downgrade na 4.7.1. a mám novou hlášku:**

Fatal error: Uncaught Exception: WC_Zasilkovna_Shipping_Method::fetch_pickup_points: failed to get content from https://www.zasilkovna.cz/api/v4/c963d8422xxx/branch.json. in /www/doc/www.adatto.cz/www/mttest/wp-content/plugins/woocommerce-zasilkovna-master/class-zasilkovna.php:211 Stack trace: #0 /www/doc/www.adatto.cz/www/mttest/wp-content/plugins/woocommerce-zasilkovna-master/class-zasilkovna.php(196): WC_Zasilkovna_Shipping_Method->fetch_pickup_points('c963d8422xxx') #1 /www/doc/www.adatto.cz/www/mttest/wp-content/plugins/woocommerce-zasilkovna-master/class-zasilkovna.php(180): WC_Zasilkovna_Shipping_Method->load_pickup_points() #2 /www/doc/www.adatto.cz/www/mttest/wp-content/plugins/woocommerce-zasilkovna-master/zasilkovna.php(73): WC_Zasilkovna_Shipping_Method->pickup_points('CZ') #3 /www/doc/www.adatto.cz/www/mttest/wp-includes/class-wp-hook.php(287): wc_zasilkovna_review_order_after_shipping('') #4 /www/doc/www.adatto.cz/www/mttest/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #5 / in /www/doc/www.adatto.cz/www/mttest/wp-content/plugins/woocommerce-zasilkovna-master/class-zasilkovna.php on line 211

Přijde mi, že si to dělá co chce.
v řádku 211 je:           throw new Exception( __METHOD__ . ": failed to get content from {$url}." );

**já tomu nerozumím na druhým webu ta hláška už zas není. Že by byl problém v tom api od zásilkovny? Na nic se nesáhlo a v 10:30 to začne fungovat normálně? Zastřelte mě, ale já tomu nerozumím. Jdu to zkusit na dalším serveru a dám vědět.**

**Comment by vyskoczilova** [comment]
Možná za to může ten json od Zásilkovny - je obrovský a třeba je tam nějaká prodleva...?

**Comment by 8915b** [comment]
@vyskoczilova Něco tam musí být, protože, aby se to SAMO zázrakem opravilo to mi hlava nebere. A na novém serveru to teď taky běží. Navíc při přihlášení do Zásilkovny jsem chytl 403. Nevěděla byste, jestli zásilkovna někde uvádí svoje verze API a XML feedu? Moc děkuji.

**Comment by vyskoczilova** [comment]
@vyskoczilova Vím jenom o tomhle: https://www.zasilkovna.cz/eshopy/implementace/xml ale v podstatě jsem se nikdy Zásilkovnou nezabývala, jen jsem šla kolem a použila to na pár testovacích webech, ale nikde to nemám a ani to aktivně nevyužívám, jen jsem opravila pár drobností

**Comment by Ayahua528** [comment]
Dobrý den, 

zaznamenávám stále tento problém 

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 23548184 bytes) in /www/doc/www.sporimevodu.cz/www/wp-includes/wp-db.php on line 3333

Verze WooCommerce: poslední 4.7.něco i 4.8.0
Verze WordPress: 5.5 i 5.6
Memory limit: 256MB
PHP verze: 7.3.25 i 7.4.13

Není už nějaké řešení?

**Comment by oerdnj** [comment]
Pokud máte s pluginem problém, který nedokážete vyřešit, tak předpokládám, že Vám @vyskoczilova ráda sdělí nabídku. Případně si myslím, že na webtrh.cz můžete také zadat poptávku a nějaký(á) programátor(ka) se Vašemu problému bude rád(a) věnovat.

Nicméně tím, že budete stále dokolečka psát, že máte problém, se něco jen těžko vyřeší.

**Comment by Ayahua528** [comment]
@oerdnj Krásný den! Tak jednak jsem sem napsal pouze jednou. Následně jsem svůj příspěvek editoval a doplnil o údaje mé konfigurace. Dále by od Vás jako spoluautora tohoto GPL pluginu bylo třeba milé, kdyby jste napsal, zda se uvažuje o dalším vývoji pluginu, který v současnosti nevyhovuje specifikaci Zásilkovny dle bodu: "V žádném případě byste neměli k seznamům poboček na našich serverech přistupovat blokujícím způsobem přímo při zobrazení košíku apod." O nabídku na placenou úpravu jsem prozatím nežádal. Díky!

**Comment by oerdnj** [comment]
> Dále by od Vás jako spoluautora tohoto GPL pluginu bylo třeba milé

Jakože ten nápis v popisu repozitáře nestačí?

**Neudržováno, e-shop, pro který to bylo vyvinuto skončil, takže se musí najít nějaký dobrovolník na údržbu.**

Zkusil jste se aspoň podívat nebo taky potřebujete, aby to zadarmo někdo udělal pro Vás?

> O nabídku na placenou úpravu jsem prozatím nežádal.

No, a to je ten problém. Open Source neznamená zadarmo. Pokud chcete plugin používat dále, tak prostě někdo bude muset nést náklady na údržbu tohoto pluginu. Nebo si holt všichni budou muset koupit funkční plugin koupit za 2,5k od Toret.cz. Nicméně, pokud by se našlo aspoň deset lidí, co by tuto částku dali na údržbu tohoto pluginu, tak by mohl existovat GPL plugin pro všechny bez oné vstupní bariéry a roční platby.

**Comment by Ayahua528** [comment]
@oerdnj  Nápisu v popisu jsem si opravdu nevšiml při stahování ani nyní, protože jsem dle výpisu chyby přišel rovnou na toto stránku a zjistil, že se to tu řeší. Domníval jsem se tedy, že je to nějakým způsobem živé téma. Poslední odstavec samozřejmě chápu. Nicméně asi nemohu zorganizovat sbírku. Za kompletně funkční řešení s roční podporou a aktualizacemi bych mohl přispět toliko, aby mě to vyšlo méně než na wordpress-moduly (tj. 1500). Prostě jen potřebuji vyřešit plugin.
